/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2022-02-07 15:12:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.co.mlec.drink.vo.DrinkVO;
import kr.co.mlec.drink.dao.DrinkDAO;
import java.util.ArrayList;
import java.net.URLEncoder;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.co.mlec.drink.dao.DrinkDAO");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("kr.co.mlec.drink.vo.DrinkVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<title>음료와 추천... 그 사이...</title>\r\n");
      out.write("<meta name=\"description\" content=\"GARO is a real-estate template\">\r\n");
      out.write("<meta name=\"author\" content=\"Kimarotec\">\r\n");
      out.write("<meta name=\"keyword\"\r\n");
      out.write("	content=\"html5, css, bootstrap, property, real-estate theme , bootstrap template\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");


 request.setCharacterEncoding("utf-8");
 
	String search= "";
	
	if(request.getParameter("search") != null){
		search = request.getParameter("search");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"slider-area\">\r\n");
      out.write("		<div class=\"slider\">\r\n");
      out.write("			<div id=\"bg-slider\" class=\"owl-carousel owl-theme\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<img src=\"assets/img/slide1/cafepic3.png\" alt=\"GTA V\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<img src=\"assets/img/slide1/cafepic2.png\" alt=\"The Last of us\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item\">\r\n");
      out.write("					<img src=\"assets/img/slide1/coffee02.jpeg\" alt=\"GTA V\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");



	
	ArrayList<DrinkVO> drinklist = new ArrayList<DrinkVO>();
	ArrayList<DrinkVO> drinklist2 = new ArrayList<DrinkVO>();

	drinklist = new DrinkDAO().DrinkSearchByname(search);
	drinklist2 = new DrinkDAO().DrinkSearchBystore(search);
	
	if(drinklist !=null)
		for(int i = 0; i<drinklist.size(); i++){
			DrinkVO search2 = drinklist.get(i); 
		}
	
	if(drinklist2 !=null)
		for(int i = 0; i<drinklist2.size(); i++){
			DrinkVO search2 = drinklist2.get(i); 
		}	
	
	


      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"slider-content\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-12\">\r\n");
      out.write("					<h2>검색창</h2>\r\n");
      out.write("					<p>당신의 음료를 찾으세요!</p>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"search-form wow pulse\" data-wow-delay=\"0.8s\">\r\n");
      out.write("\r\n");
      out.write("						<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/searchMenu.do\" method=\"get\" class=\" form-inline\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<button class=\"btn toggle-btn\" type=\"button\">\r\n");
      out.write("								<i class=\"fa fa-bars\"></i>\r\n");
      out.write("								<!--= 이거 생기는거  -->\r\n");
      out.write("							</button>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<input type=\"text\" name=\"search\" class=\"form-control\"\r\n");
      out.write("									placeholder=\"검색할 메뉴나 가게명을 입력하세요!\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<button class=\"btn search-btn\" type=\"submit\">\r\n");
      out.write("								<i class=\"fa fa-search\"></i>\r\n");
      out.write("							</button>\r\n");
      out.write("							<div style=\"display: none;\" class=\"search-toggle\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- property area -->\r\n");
      out.write("		<div class=\"content-area home-area-1 recent-property\"\r\n");
      out.write("			style=\"background-color: #FCFCFC; padding-bottom: 55px;\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"col-md-10 col-md-offset-1 col-sm-12 text-center page-title\">\r\n");
      out.write("						<!-- /.feature title -->\r\n");
      out.write("						<h2>음료 추천 & 리뷰 확인 하기</h2>\r\n");
      out.write("						<p> 음료 고민 될 때 아래의 메뉴를 이용하세요 도움이 될겁니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"row\" >\r\n");
      out.write("					<div class=\"proerty-th\">\r\n");
      out.write("					\r\n");
      out.write("						<div class=\"col-sm-6 col-md-3 p0\" >\r\n");
      out.write("							<div class=\"box-two proerty-item\">\r\n");
      out.write("								<div class=\"item-thumb\">\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drinkSuggest.do\">\r\n");
      out.write("										<img src=\"assets/img/demo/cafepic4.png\">\r\n");
      out.write("									</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item-entry overflow\">\r\n");
      out.write("									<h5>\r\n");
      out.write("									<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drinkSuggest.do\">음료 탐색 시작 </a>				\r\n");
      out.write("									</h5>\r\n");
      out.write("									<div class=\"dot-hr\"></div>\r\n");
      out.write("									<span class=\"pull-left\"> 커피메뉴 </span> <span\r\n");
      out.write("										class=\"proerty-price pull-right\">목록 보기</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("						<div class=\"col-sm-6 col-md-3 p0\">\r\n");
      out.write("							<div class=\"box-tree more-proerty text-center\">\r\n");
      out.write("								<div class=\"item-tree-icon\">\r\n");
      out.write("									<i class=\"fa fa-th\"></i>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"more-entry overflow\">\r\n");
      out.write("									<h5>\r\n");
      out.write("										<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/list.do\"> 리뷰를 확인해 보세요! </a>\r\n");
      out.write("									</h5>\r\n");
      out.write("									<h5 class=\"tree-sub-ttl\">더 나은 선택을 위해...</h5>\r\n");
      out.write("									<button class=\"btn border-btn more-black\" value=\"All properties\"\r\n");
      out.write("									 type =\"submit\"\r\n");
      out.write("									 onclick =\"location.href ='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/drinkSuggest.do'\">\r\n");
      out.write("									                     \r\n");
      out.write("									 추천받기</button>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!--다른부분-->\r\n");
      out.write("		<div class=\"testimonial-area recent-property\"\r\n");
      out.write("			style=\"background-color: #FCFCFC; padding-bottom: 15px;\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"col-md-10 col-md-offset-1 col-sm-12 text-center page-title\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<!-- /.feature title -->\r\n");
      out.write("						<h2>F4 구성원 소개</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"row testimonial\">\r\n");
      out.write("						<div class=\"col-md-12\">\r\n");
      out.write("							<div id=\"testimonial-slider\">\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"client-text\">\r\n");
      out.write("										<p>F4 리더 구준표</p>\r\n");
      out.write("										<h4>\r\n");
      out.write("											<strong>이신혜 </strong><i>Web developer</i>\r\n");
      out.write("										</h4>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"client-face wow fadeInRight\" data-wow-delay=\".9s\">\r\n");
      out.write("										<img src=\"assets/img/liger.jpg\" alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"client-text\">\r\n");
      out.write("										<p>F4 프린스송</p>\r\n");
      out.write("										<h4>\r\n");
      out.write("											<strong>최현정</strong><i>Web developer</i>\r\n");
      out.write("										</h4>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"client-face\">\r\n");
      out.write("										<img src=\"assets/img/kkangkkang2.png\" alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"client-text\">\r\n");
      out.write("										<p>F4 이정선배</p>\r\n");
      out.write("										<h4>\r\n");
      out.write("											<strong>원윤서</strong><i>Web developer</i>\r\n");
      out.write("										</h4>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"client-face\">\r\n");
      out.write("										<img src=\"assets/img/geoji.png\" alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"item\">\r\n");
      out.write("									<div class=\"client-text\">\r\n");
      out.write("										<p>F4 명예소방관</p>\r\n");
      out.write("										<h4>\r\n");
      out.write("											<strong>최윤선</strong><i>Web Developer</i>\r\n");
      out.write("										</h4>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"client-face\">\r\n");
      out.write("										<img src=\"assets/img/gwangsu.jpg\" alt=\"\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/jsp/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
